### ISSUE TITLE
'tatcli message tag' behaviour

### ISSUE THREAD

**Issue by ncrocfer** [ovh/tatcli#2]
`tatcli` allows a system user [to add tag](https://github.com/ovh/tatcli#add-a-tag-to-a-message) on his messages.

It would be great if normal users can also do it. For example, if I want to add a tag on an existing message, I must get the message (1 request), concatenate the tag with the text, and then update the message with the new text containing the tag (1 request).

Maybe `tatcli message tag <idMessage> <tag>` can do it in 1 request.

**Comment by yesnault** [comment]
I'll remove confusing action tag and untag, and adding "concat" action, to update a message by adding additional text.
